# Outline
In this notebook, we will perform model training with hyper parameter tunning

In [1]:
import numpy as np
import pandas as pd
import fastparquet

In [5]:
X_train = pd.read_csv('../data/interim/X_train_transformed.csv',index_col=0)
X_test = pd.read_csv('../data/interim/X_test_transformed.csv',index_col=0)
y_train = pd.read_csv('../data/interim/y_train.csv')
y_test = pd.read_csv('../data/interim/y_test.csv')

In [6]:
X_train.head()

,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,...,FoodCourt,ShoppingMall,Spa,VRDeck,TotalBill,CryoSleep,PassengerId,Cabin,Name,Num
4696,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.801184,1.060544,0.000000,0.000000,0.092013,False,5007_01,F/951/S,Gramus Watie,951.0
5946,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.030236,1.403965,0.766971,1.423170,0.028545,False,6308_01,G/1017/P,Jord Cofferson,1017.0
227,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.000000,0.000000,0.000000,0.000000,-0.903270,True,0244_01,NaN,Froos Sad,NaN
3950,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,-0.903270,True,4216_01,B/134/P,Rotan Dratembid,134.0
7674,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.000000,0.782453,1.479169,0.367282,0.006878,False,8191_01,G/1320/S,Gracy Gaington,1320.0

In [3]:
X_train.head()

,HomePlanet_Europa,HomePlanet_Mars,Destination_PSO J318.5-22,Destination_TRAPPIST-1e,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,...,Side,CryoSleep,Age,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Num,TotalBill
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.423756,1.672589,0.802434,1.060544,0.000000,0.000000,0.424782,0.092074
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.059170,0.000000,1.031843,1.403965,0.766971,1.417181,0.463522,0.028436
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,1.0,0.762119,0.000000,0.000000,0.000000,0.000000,0.000000,0.146339,-0.905876
3,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.445798,0.000000,0.000000,0.000000,0.000000,0.000000,-0.704127,-0.905876
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,-0.653835,0.000000,0.000000,0.782453,1.479169,0.365736,0.614107,0.006710

In [4]:
import optuna
from sklearn.model_selection import KFold,cross_validate
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [5]:
y_train

      Transported
0           False
1           False
2            True
3            True
4           False
...           ...
5819         True
5820        False
5821        False
5822        False
5823        False

[5824 rows x 1 columns]

In [50]:
def Multiple_Objective_Function(trial):
    predictor = trial.suggest_categorical('predictor', ['rf', 'lr', 'svc', 'xgb', 'light'])

    if predictor == 'rf':
        rf_n_estimators = trial.suggest_int('rf_n_estimators', 50, 200)
        rf_max_depth = trial.suggest_int('rf_max_depth', 3, 32)
        rf_min_samples_split = trial.suggest_int('rf_min_samples_split', 2, 10)
        
        model = RandomForestClassifier(
            n_estimators=rf_n_estimators, 
            max_depth=rf_max_depth, 
            min_samples_split=rf_min_samples_split,
            random_state=42
        )

    elif predictor == 'lr':
        lr_c = trial.suggest_float('lr_c', 1e-4, 1e2, log=True)
        lr_solver = trial.suggest_categorical('lr_solver', ['lbfgs', 'liblinear'])
        
        model = LogisticRegression(
            C=lr_c, 
            solver=lr_solver, 
            max_iter=2000, # Increased to help 'lbfgs' converge
            random_state=42
        )

    elif predictor == 'svc':
        svc_c = trial.suggest_float('svc_c', 1e-3, 1e2, log=True)
        svc_kernel = trial.suggest_categorical('svc_kernel', ['linear', 'rbf'])
        svc_gamma = trial.suggest_categorical('svc_gamma', ['scale', 'auto'])
        
        model = SVC(
            C=svc_c, 
            kernel=svc_kernel, 
            gamma=svc_gamma,
            random_state=42
        )

    elif predictor == 'xgb':
        xgb_n_estimators = trial.suggest_int('xgb_n_estimators', 50, 200)
        xgb_lr = trial.suggest_float('xgb_lr', 1e-3, 0.3, log=True)
        xgb_max_depth = trial.suggest_int('xgb_max_depth', 3, 9)
        xgb_subsample = trial.suggest_float('xgb_subsample', 0.5, 1.0)
        
        model = XGBClassifier(
            n_estimators=xgb_n_estimators, 
            learning_rate=xgb_lr, 
            max_depth=xgb_max_depth,
            subsample=xgb_subsample,
            random_state=42
        )

    elif predictor == 'light':
        light_n_estimators = trial.suggest_int('light_n_estimators', 50, 200)
        light_lr = trial.suggest_float('light_lr', 1e-3, 0.3, log=True)
        light_num_leaves = trial.suggest_int('light_num_leaves', 20, 100)
        light_subsample = trial.suggest_float('light_subsample', 0.5, 1.0)
        
        model = LGBMClassifier(
            n_estimators=light_n_estimators, 
            learning_rate=light_lr, 
            num_leaves=light_num_leaves,
            subsample=light_subsample,
            random_state=42,
            verbose=-1 # Silences LightGBM terminal warnings
        )

    cv_strategy = KFold(n_splits=5, shuffle=True, random_state=42)

    cv_results = cross_validate(
        model,
        X_train,
        y_train['Transported'],
        scoring='accuracy',
        cv=cv_strategy,
        return_train_score=True,
        n_jobs=-1
    )

    train_score_mean = cv_results['train_score'].mean()
    val_score_mean = cv_results['test_score'].mean()

    trial.set_user_attr('train_score_mean', train_score_mean)
    trial.set_user_attr('train_score_std', cv_results['train_score'].std())
    trial.set_user_attr('test_score_std', cv_results['test_score'].std())
    trial.set_user_attr('overfitting_gap', train_score_mean - val_score_mean)
    

    return (val_score_mean)

In [45]:
multiple_study = optuna.create_study(direction='maximize',study_name='Model_Selection')

[I 2026-07-27 10:53:06,810] A new study created in memory with name: Model_Selection

In [46]:
multiple_study.optimize(Multiple_Objective_Function,n_trials=30,n_jobs=-1)

[I 2026-07-27 10:53:13,891] Trial 2 finished with value: 0.8044290075660369 and parameters: {'predictor': 'rf', 'rf_n_estimators': 147, 'rf_max_depth': 24, 'rf_min_samples_split': 6}. Best is trial 2 with value: 0.8044290075660369.
[I 2026-07-27 10:53:15,656] Trial 3 finished with value: 0.7925808592540153 and parameters: {'predictor': 'xgb', 'xgb_n_estimators': 192, 'xgb_lr': 0.21475612809870417, 'xgb_max_depth': 7, 'xgb_subsample': 0.5446043235538645}. Best is trial 2 with value: 0.8044290075660369.
[I 2026-07-27 10:53:22,066] Trial 1 finished with value: 0.7893192041650073 and parameters: {'predictor': 'xgb', 'xgb_n_estimators': 118, 'xgb_lr': 0.0015197707181302134, 'xgb_max_depth': 6, 'xgb_subsample': 0.5630478033756084}. Best is trial 2 with value: 0.8044290075660369.
[I 2026-07-27 10:53:24,790] Trial 4 finished with value: 0.7955013789950296 and parameters: {'predictor': 'light', 'light_n_estimators': 80, 'light_lr': 0.01818234814963735, 'light_num_leaves': 87, 'light_subsample': 0.639103661527197}. Best is trial 2 with value: 0.8044290075660369.
[I 2026-07-27 10:53:26,204] Trial 5 finished with value: 0.8087221804344941 and parameters: {'predictor': 'light', 'light_n_estimators': 87, 'light_lr': 0.1579053991787715, 'light_num_leaves': 34, 'light_subsample': 0.6863906394524826}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:28,337] Trial 6 finished with value: 0.7987636240284353 and parameters: {'predictor': 'xgb', 'xgb_n_estimators': 62, 'xgb_lr': 0.010878313388256702, 'xgb_max_depth': 9, 'xgb_subsample': 0.7807767674017783}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:28,787] Trial 0 finished with value: 0.8044293025382357 and parameters: {'predictor': 'svc', 'svc_c': 1.3081179853563278, 'svc_kernel': 'rbf', 'svc_gamma': 'scale'}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:29,917] Trial 7 finished with value: 0.8064917481527367 and parameters: {'predictor': 'xgb', 'xgb_n_estimators': 110, 'xgb_lr': 0.04207114335817773, 'xgb_max_depth': 7, 'xgb_subsample': 0.7878960122862215}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:39,323] Trial 9 finished with value: 0.7901791956108136 and parameters: {'predictor': 'rf', 'rf_n_estimators': 128, 'rf_max_depth': 7, 'rf_min_samples_split': 7}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:41,656] Trial 8 finished with value: 0.7750689497514859 and parameters: {'predictor': 'svc', 'svc_c': 6.531093314042483, 'svc_kernel': 'linear', 'svc_gamma': 'auto'}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:42,176] Trial 10 finished with value: 0.8040868398153475 and parameters: {'predictor': 'rf', 'rf_n_estimators': 107, 'rf_max_depth': 10, 'rf_min_samples_split': 10}. Best is trial 5 with value: 0.8087221804344941.
[I 2026-07-27 10:53:45,082] Trial 11 finished with value: 0.8095808445054054 and parameters: {'predictor': 'light', 'light_n_estimators': 200, 'light_lr': 0.05161066863412421, 'light_num_leaves': 37, 'light_subsample': 0.95635005469758}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:45,623] Trial 12 finished with value: 0.7973897910121971 and parameters: {'predictor': 'xgb', 'xgb_n_estimators': 69, 'xgb_lr': 0.001637990246838515, 'xgb_max_depth': 9, 'xgb_subsample': 0.6458808167362546}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:46,573] Trial 14 finished with value: 0.747079922717284 and parameters: {'predictor': 'lr', 'lr_c': 0.0007041574086751207, 'lr_solver': 'lbfgs'}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:47,226] Trial 13 finished with value: 0.8035719658422193 and parameters: {'predictor': 'light', 'light_n_estimators': 164, 'light_lr': 0.28647367990255607, 'light_num_leaves': 21, 'light_subsample': 0.896582333409738}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:49,153] Trial 15 finished with value: 0.8004790348509653 and parameters: {'predictor': 'light', 'light_n_estimators': 197, 'light_lr': 0.24200717374164357, 'light_num_leaves': 29, 'light_subsample': 0.9850740388715965}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:50,565] Trial 16 finished with value: 0.7927535654764537 and parameters: {'predictor': 'light', 'light_n_estimators': 186, 'light_lr': 0.24571764226105577, 'light_num_leaves': 27, 'light_subsample': 0.9837580870305573}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:51,828] Trial 17 finished with value: 0.7965297995663908 and parameters: {'predictor': 'light', 'light_n_estimators': 199, 'light_lr': 0.26062960907784205, 'light_num_leaves': 24, 'light_subsample': 0.9771149693796576}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:53,095] Trial 18 finished with value: 0.8064902732917423 and parameters: {'predictor': 'light', 'light_n_estimators': 97, 'light_lr': 0.10680850613581579, 'light_num_leaves': 34, 'light_subsample': 0.9969397875622813}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:54,420] Trial 19 finished with value: 0.807005737209268 and parameters: {'predictor': 'light', 'light_n_estimators': 88, 'light_lr': 0.03418960556178955, 'light_num_leaves': 48, 'light_subsample': 0.735646647281708}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:55,101] Trial 21 finished with value: 0.7721507897880625 and parameters: {'predictor': 'lr', 'lr_c': 77.37763521644204, 'lr_solver': 'liblinear'}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:55,369] Trial 22 finished with value: 0.7721507897880625 and parameters: {'predictor': 'lr', 'lr_c': 64.27859185431015, 'lr_solver': 'liblinear'}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:55,579] Trial 23 finished with value: 0.7721507897880625 and parameters: {'predictor': 'lr', 'lr_c': 40.757637548784, 'lr_solver': 'liblinear'}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:55,780] Trial 20 finished with value: 0.8030573868412902 and parameters: {'predictor': 'light', 'light_n_estimators': 87, 'light_lr': 0.024895593202721465, 'light_num_leaves': 53, 'light_subsample': 0.742201469139276}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:56,865] Trial 24 finished with value: 0.7956732003008715 and parameters: {'predictor': 'light', 'light_n_estimators': 51, 'light_lr': 0.026902775788540823, 'light_num_leaves': 54, 'light_subsample': 0.7266610067919728}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:57,653] Trial 25 finished with value: 0.7982487500553074 and parameters: {'predictor': 'light', 'light_n_estimators': 54, 'light_lr': 0.03000022030669607, 'light_num_leaves': 54, 'light_subsample': 0.731606149953327}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:58,357] Trial 26 finished with value: 0.7977340235682787 and parameters: {'predictor': 'light', 'light_n_estimators': 53, 'light_lr': 0.02850972823022412, 'light_num_leaves': 52, 'light_subsample': 0.7230031853344867}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:53:59,062] Trial 27 finished with value: 0.8039156084539032 and parameters: {'predictor': 'light', 'light_n_estimators': 50, 'light_lr': 0.05003132737628808, 'light_num_leaves': 50, 'light_subsample': 0.7439908477378454}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:54:01,473] Trial 28 finished with value: 0.7846834210875625 and parameters: {'predictor': 'light', 'light_n_estimators': 131, 'light_lr': 0.0014178913418113463, 'light_num_leaves': 47, 'light_subsample': 0.6059942842181586}. Best is trial 11 with value: 0.8095808445054054.
[I 2026-07-27 10:54:02,364] Trial 29 finished with value: 0.808207306461366 and parameters: {'predictor': 'light', 'light_n_estimators': 128, 'light_lr': 0.06880405618047052, 'light_num_leaves': 42, 'light_subsample': 0.5215368107454178}. Best is trial 11 with value: 0.8095808445054054.

In [47]:
df = multiple_study.trials_dataframe()

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   number                       30 non-null     int64
 1   value                        30 non-null     float64
 2   datetime_start               30 non-null     datetime64[ns]
 3   datetime_complete            30 non-null     datetime64[ns]
 4   duration                     30 non-null     timedelta64[ns]
 5   params_light_lr              16 non-null     float64
 6   params_light_n_estimators    16 non-null     float64
 7   params_light_num_leaves      16 non-null     float64
 8   params_light_subsample       16 non-null     float64
 9   params_lr_c                  4 non-null      float64
 10  params_lr_solver             4 non-null      object
 11  params_predictor             30 non-null     object
 12  params_rf_max_depth          3 non-null      float64
 13  params_rf_min_samples_split  3 non-null      float64
 14  params_rf_n_estimators       3 non-null      float64
 15  params_svc_c                 2 non-null      float64
 16  params_svc_gamma             2 non-null      object
 17  params_svc_kernel            2 non-null      object
 18  params_xgb_lr                5 non-null      float64
 19  params_xgb_max_depth         5 non-null      float64
 20  params_xgb_n_estimators      5 non-null      float64
 21  params_xgb_subsample         5 non-null      float64
 22  user_attrs_Predictor         30 non-null     object
 23  user_attrs_overfitting_gap   30 non-null     float64
 24  user_attrs_test_score_std    30 non-null     float64
 25  user_attrs_train_score_mean  30 non-null     float64
 26  user_attrs_train_score_std   30 non-null     float64
 27  state                        30 non-null     object
dtypes: datetime64[ns](2), float64(18), int64(1), object(6), timedelta64[ns](1)
memory usage: 6.7+ KB

In [52]:
df.groupby("params_predictor")['value'].mean().sort_values()

params_predictor
lr       0.765883
svc      0.789749
xgb      0.796909
rf       0.799565
light    0.800760
Name: value, dtype: float64

In [53]:
df.groupby("params_predictor")['user_attrs_overfitting_gap'].mean().sort_values()

params_predictor
lr       0.005709
svc      0.015089
rf       0.081731
xgb      0.097931
light    0.111980
Name: user_attrs_overfitting_gap, dtype: float64

In [55]:
df.sort_values(by=['value','user_attrs_overfitting_gap'],ascending=[False,True]).head()

,number,value,datetime_start,datetime_complete,duration,params_light_lr,params_light_n_estimators,params_light_num_leaves,params_light_subsample,params_lr_c,...,params_xgb_lr,params_xgb_max_depth,params_xgb_n_estimators,params_xgb_subsample,user_attrs_Predictor,user_attrs_overfitting_gap,user_attrs_test_score_std,user_attrs_train_score_mean,user_attrs_train_score_std,state
11,11,0.809581,2026-07-27 10:53:29.921491,2026-07-27 10:53:45.081856,0 days 00:00:15.160365,0.051611,200.0,37.0,0.956350,NaN,...,NaN,NaN,NaN,NaN,light,0.129121,0.009872,0.938702,0.003299,COMPLETE
5,5,0.808722,2026-07-27 10:53:15.665419,2026-07-27 10:53:26.204214,0 days 00:00:10.538795,0.157905,87.0,34.0,0.686391,NaN,...,NaN,NaN,NaN,NaN,light,0.141784,0.007732,0.950507,0.001249,COMPLETE
29,29,0.808207,2026-07-27 10:53:57.657760,2026-07-27 10:54:02.364157,0 days 00:00:04.706397,0.068804,128.0,42.0,0.521537,NaN,...,NaN,NaN,NaN,NaN,light,0.129207,0.008210,0.937414,0.002709,COMPLETE
19,19,0.807006,2026-07-27 10:53:49.157237,2026-07-27 10:53:54.420146,0 days 00:00:05.262909,0.034190,88.0,48.0,0.735647,NaN,...,NaN,NaN,NaN,NaN,light,0.070141,0.007017,0.877146,0.002467,COMPLETE
7,7,0.806492,2026-07-27 10:53:24.795731,2026-07-27 10:53:29.917312,0 days 00:00:05.121581,NaN,NaN,NaN,NaN,NaN,...,0.042071,7.0,110.0,0.787896,xgb,0.088168,0.008320,0.894660,0.001556,COMPLETE

In [7]:

def rf_objective(trial):
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'max_depth': trial.suggest_int('max_depth', 3, 12), 
        'min_samples_split': trial.suggest_int('min_samples_split', 5, 30),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 2, 15),
        'max_features': trial.suggest_float('max_features', 0.4, 0.8),
        'max_samples': trial.suggest_float('max_samples', 0.5, 0.9),
        'random_state': 42,
        'n_jobs': -1
    }
    
    model = RandomForestClassifier(**param)
    
    cv_strategy = KFold(n_splits=5, shuffle=True, random_state=42)

    cv_results = cross_validate(
        model,
        X_train,
        y_train['Transported'],
        scoring='accuracy',
        cv=cv_strategy,
        return_train_score=True,
        n_jobs=-1
    )

    train_score_mean = cv_results['train_score'].mean()
    val_score_mean = cv_results['test_score'].mean()

    # Log metrics to the Optuna trial
    trial.set_user_attr('train_score_mean', train_score_mean)
    trial.set_user_attr('train_score_std', cv_results['train_score'].std())
    trial.set_user_attr('test_score_std', cv_results['test_score'].std())
    trial.set_user_attr('overfitting_gap', train_score_mean - val_score_mean)
    
    return val_score_mean

def lgb_objective(trial):
    param = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 500),
        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.1, log=True),
        'max_depth': trial.suggest_int('max_depth', 3, 8),
        'num_leaves': trial.suggest_int('num_leaves', 10, 50), 
        'min_child_samples': trial.suggest_int('min_child_samples', 20, 100),
        'reg_alpha': trial.suggest_float('reg_alpha', 1e-4, 10.0, log=True),
        'reg_lambda': trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
        'subsample': trial.suggest_float('subsample', 0.5, 0.9),
        'subsample_freq': trial.suggest_int('subsample_freq', 1, 5),
        'colsample_bytree': trial.suggest_float('colsample_bytree', 0.4, 0.8),
        'random_state': 42,
        'verbose': -1
    }
    
    model = LGBMClassifier(**param)
    
    cv_strategy = KFold(n_splits=5, shuffle=True, random_state=42)

    cv_results = cross_validate(
        model,
        X_train,
        y_train['Transported'],
        scoring='accuracy',
        cv=cv_strategy,
        return_train_score=True,
        n_jobs=-1
    )

    train_score_mean = cv_results['train_score'].mean()
    val_score_mean = cv_results['test_score'].mean()

    trial.set_user_attr('train_score_mean', train_score_mean)
    trial.set_user_attr('train_score_std', cv_results['train_score'].std())
    trial.set_user_attr('test_score_std', cv_results['test_score'].std())
    trial.set_user_attr('overfitting_gap', train_score_mean - val_score_mean)
    
    return val_score_mean

In [57]:
rf_study = optuna.create_study(direction='maximize')
rf_study.optimize(rf_objective,n_trials=30)

[I 2026-07-27 11:23:34,787] A new study created in memory with name: no-name-981762dd-461f-424e-82f2-c026c92e3744
[I 2026-07-27 11:23:48,139] Trial 0 finished with value: 0.7867430644661739 and parameters: {'n_estimators': 219, 'max_depth': 4, 'min_samples_split': 6, 'min_samples_leaf': 15, 'max_features': 0.5293756815522709, 'max_samples': 0.6356091084400788}. Best is trial 0 with value: 0.7867430644661739.
[I 2026-07-27 11:23:58,015] Trial 1 finished with value: 0.8011673524770291 and parameters: {'n_estimators': 206, 'max_depth': 11, 'min_samples_split': 29, 'min_samples_leaf': 3, 'max_features': 0.7822456539518257, 'max_samples': 0.560685948371605}. Best is trial 1 with value: 0.8011673524770291.
[I 2026-07-27 11:24:08,081] Trial 2 finished with value: 0.7639061693435394 and parameters: {'n_estimators': 356, 'max_depth': 3, 'min_samples_split': 18, 'min_samples_leaf': 3, 'max_features': 0.7213186848494784, 'max_samples': 0.6040754324329101}. Best is trial 1 with value: 0.8011673524770291.
[I 2026-07-27 11:24:11,594] Trial 3 finished with value: 0.7941282834092886 and parameters: {'n_estimators': 104, 'max_depth': 5, 'min_samples_split': 16, 'min_samples_leaf': 5, 'max_features': 0.48217735199304174, 'max_samples': 0.5632437081947054}. Best is trial 1 with value: 0.8011673524770291.
[I 2026-07-27 11:24:21,908] Trial 4 finished with value: 0.7996227305576449 and parameters: {'n_estimators': 252, 'max_depth': 6, 'min_samples_split': 10, 'min_samples_leaf': 6, 'max_features': 0.5927474881839763, 'max_samples': 0.7361705740922205}. Best is trial 1 with value: 0.8011673524770291.
[I 2026-07-27 11:24:38,662] Trial 5 finished with value: 0.8025416279515655 and parameters: {'n_estimators': 397, 'max_depth': 10, 'min_samples_split': 19, 'min_samples_leaf': 8, 'max_features': 0.5192080685583259, 'max_samples': 0.6326797991062287}. Best is trial 5 with value: 0.8025416279515655.
[I 2026-07-27 11:24:51,393] Trial 6 finished with value: 0.7800467530935209 and parameters: {'n_estimators': 488, 'max_depth': 4, 'min_samples_split': 13, 'min_samples_leaf': 15, 'max_features': 0.4482708308266191, 'max_samples': 0.7006317591028688}. Best is trial 5 with value: 0.8025416279515655.
[I 2026-07-27 11:24:56,129] Trial 7 finished with value: 0.8016829638806543 and parameters: {'n_estimators': 107, 'max_depth': 9, 'min_samples_split': 29, 'min_samples_leaf': 14, 'max_features': 0.4583888532954803, 'max_samples': 0.7993499547519065}. Best is trial 5 with value: 0.8025416279515655.
[I 2026-07-27 11:25:05,788] Trial 8 finished with value: 0.7616745571729864 and parameters: {'n_estimators': 371, 'max_depth': 3, 'min_samples_split': 29, 'min_samples_leaf': 15, 'max_features': 0.4977180004850976, 'max_samples': 0.500471406085252}. Best is trial 5 with value: 0.8025416279515655.
[I 2026-07-27 11:25:20,563] Trial 9 finished with value: 0.801340206185567 and parameters: {'n_estimators': 420, 'max_depth': 6, 'min_samples_split': 15, 'min_samples_leaf': 14, 'max_features': 0.5818584740788117, 'max_samples': 0.8034005075853663}. Best is trial 5 with value: 0.8025416279515655.
[I 2026-07-27 11:25:47,572] Trial 10 finished with value: 0.8040862498709498 and parameters: {'n_estimators': 495, 'max_depth': 12, 'min_samples_split': 21, 'min_samples_leaf': 10, 'max_features': 0.6939288082433656, 'max_samples': 0.896534269674241}. Best is trial 10 with value: 0.8040862498709498.
[I 2026-07-27 11:26:16,300] Trial 11 finished with value: 0.8027127118269103 and parameters: {'n_estimators': 500, 'max_depth': 12, 'min_samples_split': 22, 'min_samples_leaf': 10, 'max_features': 0.676776291913247, 'max_samples': 0.8991087240145748}. Best is trial 10 with value: 0.8040862498709498.
[I 2026-07-27 11:26:44,802] Trial 12 finished with value: 0.8032283232305355 and parameters: {'n_estimators': 497, 'max_depth': 12, 'min_samples_split': 22, 'min_samples_leaf': 11, 'max_features': 0.6831597819502697, 'max_samples': 0.8909228058946383}. Best is trial 10 with value: 0.8040862498709498.
[I 2026-07-27 11:27:11,225] Trial 13 finished with value: 0.804944913941861 and parameters: {'n_estimators': 436, 'max_depth': 12, 'min_samples_split': 23, 'min_samples_leaf': 11, 'max_features': 0.6675601255961607, 'max_samples': 0.8916990554284869}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:27:30,867] Trial 14 finished with value: 0.7994507617657035 and parameters: {'n_estimators': 442, 'max_depth': 8, 'min_samples_split': 25, 'min_samples_leaf': 11, 'max_features': 0.6424925265587017, 'max_samples': 0.8399740825851466}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:27:48,485] Trial 15 finished with value: 0.8015114375470113 and parameters: {'n_estimators': 312, 'max_depth': 10, 'min_samples_split': 22, 'min_samples_leaf': 9, 'max_features': 0.7604345262456454, 'max_samples': 0.8495363842648236}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:28:09,818] Trial 16 finished with value: 0.8008235623792457 and parameters: {'n_estimators': 445, 'max_depth': 11, 'min_samples_split': 25, 'min_samples_leaf': 12, 'max_features': 0.6351993677964962, 'max_samples': 0.7559466802111123}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:28:22,562] Trial 17 finished with value: 0.801340206185567 and parameters: {'n_estimators': 331, 'max_depth': 8, 'min_samples_split': 26, 'min_samples_leaf': 7, 'max_features': 0.40098202852015874, 'max_samples': 0.8494178165324365}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:28:46,094] Trial 18 finished with value: 0.8016829638806542 and parameters: {'n_estimators': 458, 'max_depth': 12, 'min_samples_split': 20, 'min_samples_leaf': 13, 'max_features': 0.7240603865719634, 'max_samples': 0.7970961050716548}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:29:07,719] Trial 19 finished with value: 0.8023701016179224 and parameters: {'n_estimators': 390, 'max_depth': 10, 'min_samples_split': 11, 'min_samples_leaf': 9, 'max_features': 0.733786659287604, 'max_samples': 0.8795986182066104}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:29:20,586] Trial 20 finished with value: 0.8020264590062386 and parameters: {'n_estimators': 283, 'max_depth': 11, 'min_samples_split': 26, 'min_samples_leaf': 12, 'max_features': 0.5563316374836949, 'max_samples': 0.724543750484735}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:29:47,170] Trial 21 finished with value: 0.8033998495641785 and parameters: {'n_estimators': 499, 'max_depth': 12, 'min_samples_split': 22, 'min_samples_leaf': 10, 'max_features': 0.6657720434247547, 'max_samples': 0.8852748617216779}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:30:12,399] Trial 22 finished with value: 0.8021978378537824 and parameters: {'n_estimators': 467, 'max_depth': 12, 'min_samples_split': 21, 'min_samples_leaf': 10, 'max_features': 0.6477428813470052, 'max_samples': 0.8363850970342253}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:30:36,001] Trial 23 finished with value: 0.8033997020780792 and parameters: {'n_estimators': 420, 'max_depth': 9, 'min_samples_split': 24, 'min_samples_leaf': 8, 'max_features': 0.6855998263370691, 'max_samples': 0.8674163230248282}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:30:58,642] Trial 24 finished with value: 0.8032283232305355 and parameters: {'n_estimators': 463, 'max_depth': 11, 'min_samples_split': 18, 'min_samples_leaf': 10, 'max_features': 0.6263409418141482, 'max_samples': 0.7802404791802156}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:31:20,682] Trial 25 finished with value: 0.8037434921758624 and parameters: {'n_estimators': 418, 'max_depth': 12, 'min_samples_split': 23, 'min_samples_leaf': 12, 'max_features': 0.6916212697401457, 'max_samples': 0.8281019602591524}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:31:41,743] Trial 26 finished with value: 0.8004813946285563 and parameters: {'n_estimators': 417, 'max_depth': 9, 'min_samples_split': 27, 'min_samples_leaf': 12, 'max_features': 0.6979493377829724, 'max_samples': 0.8138175046240987}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:32:01,828] Trial 27 finished with value: 0.8023696591596241 and parameters: {'n_estimators': 352, 'max_depth': 11, 'min_samples_split': 24, 'min_samples_leaf': 11, 'max_features': 0.7558401989288942, 'max_samples': 0.8275018229720845}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:32:22,830] Trial 28 finished with value: 0.8020266064923381 and parameters: {'n_estimators': 393, 'max_depth': 10, 'min_samples_split': 15, 'min_samples_leaf': 13, 'max_features': 0.7887068149175834, 'max_samples': 0.7644940401719333}. Best is trial 13 with value: 0.804944913941861.
[I 2026-07-27 11:32:29,891] Trial 29 finished with value: 0.8030557644941965 and parameters: {'n_estimators': 148, 'max_depth': 12, 'min_samples_split': 7, 'min_samples_leaf': 13, 'max_features': 0.6182167256232731, 'max_samples': 0.6745488511119763}. Best is trial 13 with value: 0.804944913941861.

In [8]:
lgb_study = optuna.create_study(direction='maximize')
lgb_study.optimize(lgb_objective,n_trials=30)

[I 2026-07-28 09:48:49,471] A new study created in memory with name: no-name-58a92582-3f7f-4ab5-b6d1-e1e5d5edac35
[I 2026-07-28 09:49:08,890] Trial 0 finished with value: 0.804773387608218 and parameters: {'n_estimators': 422, 'learning_rate': 0.0468457412741649, 'max_depth': 3, 'num_leaves': 30, 'min_child_samples': 93, 'reg_alpha': 0.005661152061764648, 'reg_lambda': 0.16466636390464387, 'subsample': 0.8309149782256302, 'subsample_freq': 3, 'colsample_bytree': 0.4106612901567255}. Best is trial 0 with value: 0.804773387608218.
[I 2026-07-28 09:49:14,243] Trial 1 finished with value: 0.8107828562158016 and parameters: {'n_estimators': 380, 'learning_rate': 0.03656924693016446, 'max_depth': 7, 'num_leaves': 49, 'min_child_samples': 39, 'reg_alpha': 0.0219168317426632, 'reg_lambda': 1.824836683717424, 'subsample': 0.877554342097719, 'subsample_freq': 5, 'colsample_bytree': 0.4242808297771443}. Best is trial 1 with value: 0.8107828562158016.
[I 2026-07-28 09:49:15,917] Trial 2 finished with value: 0.8047732401221184 and parameters: {'n_estimators': 215, 'learning_rate': 0.04154763256703522, 'max_depth': 3, 'num_leaves': 18, 'min_child_samples': 98, 'reg_alpha': 0.00393599714856964, 'reg_lambda': 0.00021822214308581572, 'subsample': 0.8609409508876296, 'subsample_freq': 1, 'colsample_bytree': 0.5659326938119918}. Best is trial 1 with value: 0.8107828562158016.
[I 2026-07-28 09:49:18,585] Trial 3 finished with value: 0.8121565417459404 and parameters: {'n_estimators': 250, 'learning_rate': 0.06910153509867809, 'max_depth': 6, 'num_leaves': 14, 'min_child_samples': 96, 'reg_alpha': 0.001262566024497075, 'reg_lambda': 0.0012170730566926984, 'subsample': 0.799840728682117, 'subsample_freq': 1, 'colsample_bytree': 0.5729715434535657}. Best is trial 3 with value: 0.8121565417459404.
[I 2026-07-28 09:49:23,018] Trial 4 finished with value: 0.8106114773682581 and parameters: {'n_estimators': 367, 'learning_rate': 0.027519713924512922, 'max_depth': 5, 'num_leaves': 48, 'min_child_samples': 74, 'reg_alpha': 0.2131136217168666, 'reg_lambda': 0.7451455958668184, 'subsample': 0.7779073038923274, 'subsample_freq': 2, 'colsample_bytree': 0.4400561239378553}. Best is trial 3 with value: 0.8121565417459404.
[I 2026-07-28 09:49:26,384] Trial 5 finished with value: 0.81232895299618 and parameters: {'n_estimators': 320, 'learning_rate': 0.025518213413288353, 'max_depth': 6, 'num_leaves': 13, 'min_child_samples': 48, 'reg_alpha': 0.061302991810937756, 'reg_lambda': 0.7395321010793007, 'subsample': 0.6411920836210615, 'subsample_freq': 4, 'colsample_bytree': 0.6887209904817726}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:30,687] Trial 6 finished with value: 0.8073464300989631 and parameters: {'n_estimators': 466, 'learning_rate': 0.07544843647657015, 'max_depth': 7, 'num_leaves': 28, 'min_child_samples': 68, 'reg_alpha': 0.04381287224800892, 'reg_lambda': 0.00024667444270953885, 'subsample': 0.5393687595186042, 'subsample_freq': 3, 'colsample_bytree': 0.4682203763594878}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:32,623] Trial 7 finished with value: 0.8015112900609118 and parameters: {'n_estimators': 264, 'learning_rate': 0.019719321699510173, 'max_depth': 4, 'num_leaves': 18, 'min_child_samples': 86, 'reg_alpha': 0.0027395643627732627, 'reg_lambda': 0.0003065032657672804, 'subsample': 0.7362143708396633, 'subsample_freq': 3, 'colsample_bytree': 0.5727869823766395}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:35,098] Trial 8 finished with value: 0.8107824137575033 and parameters: {'n_estimators': 217, 'learning_rate': 0.08678601958964037, 'max_depth': 7, 'num_leaves': 26, 'min_child_samples': 89, 'reg_alpha': 0.0006085378532874982, 'reg_lambda': 0.0001236845556303883, 'subsample': 0.6596918223100331, 'subsample_freq': 5, 'colsample_bytree': 0.7930010586177662}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:44,169] Trial 9 finished with value: 0.810267834756574 and parameters: {'n_estimators': 456, 'learning_rate': 0.03221001531445988, 'max_depth': 7, 'num_leaves': 21, 'min_child_samples': 22, 'reg_alpha': 0.10309068144705502, 'reg_lambda': 1.2909620631134033, 'subsample': 0.5050140893689249, 'subsample_freq': 2, 'colsample_bytree': 0.5503684155230726}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:45,746] Trial 10 finished with value: 0.7936131144639618 and parameters: {'n_estimators': 150, 'learning_rate': 0.011054073829016546, 'max_depth': 5, 'num_leaves': 38, 'min_child_samples': 46, 'reg_alpha': 7.24771528046895, 'reg_lambda': 0.017142483436862067, 'subsample': 0.6228654875285232, 'subsample_freq': 4, 'colsample_bytree': 0.7321572695171162}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:48,236] Trial 11 finished with value: 0.8083795702255061 and parameters: {'n_estimators': 305, 'learning_rate': 0.017132472589792887, 'max_depth': 6, 'num_leaves': 12, 'min_child_samples': 55, 'reg_alpha': 0.00012181814438491356, 'reg_lambda': 0.0058440316601764955, 'subsample': 0.5972114193330804, 'subsample_freq': 1, 'colsample_bytree': 0.6642545817094674}. Best is trial 5 with value: 0.81232895299618.
[I 2026-07-28 09:49:52,087] Trial 12 finished with value: 0.8124997418993261 and parameters: {'n_estimators': 319, 'learning_rate': 0.05916006158291774, 'max_depth': 6, 'num_leaves': 10, 'min_child_samples': 30, 'reg_alpha': 3.6202718922173323, 'reg_lambda': 9.996470826535594, 'subsample': 0.7196113978680685, 'subsample_freq': 4, 'colsample_bytree': 0.6547144608827793}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:49:55,476] Trial 13 finished with value: 0.8114702889252687 and parameters: {'n_estimators': 331, 'learning_rate': 0.055123534698235596, 'max_depth': 8, 'num_leaves': 10, 'min_child_samples': 25, 'reg_alpha': 1.876296142955838, 'reg_lambda': 9.985909153670324, 'subsample': 0.7022009554498183, 'subsample_freq': 4, 'colsample_bytree': 0.6628366218124747}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:49:56,734] Trial 14 finished with value: 0.7999660781971298 and parameters: {'n_estimators': 106, 'learning_rate': 0.022720969144599732, 'max_depth': 5, 'num_leaves': 37, 'min_child_samples': 36, 'reg_alpha': 0.32127953631572487, 'reg_lambda': 9.304965614912499, 'subsample': 0.6734501335986813, 'subsample_freq': 4, 'colsample_bytree': 0.656882706244026}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:00,367] Trial 15 finished with value: 0.8051180626225978 and parameters: {'n_estimators': 343, 'learning_rate': 0.014068573260637103, 'max_depth': 6, 'num_leaves': 23, 'min_child_samples': 53, 'reg_alpha': 1.8804286331951472, 'reg_lambda': 0.11052833923767, 'subsample': 0.7311383352968603, 'subsample_freq': 4, 'colsample_bytree': 0.7273449056246961}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:03,269] Trial 16 finished with value: 0.8085510965591494 and parameters: {'n_estimators': 280, 'learning_rate': 0.05899959867393482, 'max_depth': 8, 'num_leaves': 16, 'min_child_samples': 33, 'reg_alpha': 1.0118510083454415, 'reg_lambda': 0.38420700064801727, 'subsample': 0.5902180950793254, 'subsample_freq': 5, 'colsample_bytree': 0.6261270434125243}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:07,235] Trial 17 finished with value: 0.8090656755600785 and parameters: {'n_estimators': 391, 'learning_rate': 0.02845554863243597, 'max_depth': 6, 'num_leaves': 35, 'min_child_samples': 45, 'reg_alpha': 9.103053314643436, 'reg_lambda': 2.79580498525445, 'subsample': 0.6468145507675109, 'subsample_freq': 4, 'colsample_bytree': 0.7272518280892961}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:09,783] Trial 18 finished with value: 0.8095812869637037 and parameters: {'n_estimators': 317, 'learning_rate': 0.09331608613503223, 'max_depth': 4, 'num_leaves': 10, 'min_child_samples': 66, 'reg_alpha': 0.01478487644030616, 'reg_lambda': 0.07270588588949001, 'subsample': 0.7509910061369072, 'subsample_freq': 2, 'colsample_bytree': 0.510139246350595}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:11,537] Trial 19 finished with value: 0.8078655811689748 and parameters: {'n_estimators': 200, 'learning_rate': 0.04752465318103299, 'max_depth': 4, 'num_leaves': 21, 'min_child_samples': 30, 'reg_alpha': 0.579143817566607, 'reg_lambda': 4.186817314578951, 'subsample': 0.6905534925655294, 'subsample_freq': 3, 'colsample_bytree': 0.7863202467194974}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:15,350] Trial 20 finished with value: 0.8102682772148725 and parameters: {'n_estimators': 416, 'learning_rate': 0.024445329221951372, 'max_depth': 5, 'num_leaves': 44, 'min_child_samples': 45, 'reg_alpha': 0.09939175687206671, 'reg_lambda': 0.37576710941418506, 'subsample': 0.5658664445898023, 'subsample_freq': 5, 'colsample_bytree': 0.6980165774148737}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:17,558] Trial 21 finished with value: 0.8106119198265563 and parameters: {'n_estimators': 260, 'learning_rate': 0.06823020741473458, 'max_depth': 6, 'num_leaves': 14, 'min_child_samples': 74, 'reg_alpha': 0.0005461188815948488, 'reg_lambda': 0.0013174735608607916, 'subsample': 0.8064685068561014, 'subsample_freq': 4, 'colsample_bytree': 0.6033314773955047}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:19,617] Trial 22 finished with value: 0.8092376443520198 and parameters: {'n_estimators': 243, 'learning_rate': 0.06374476000191422, 'max_depth': 6, 'num_leaves': 15, 'min_child_samples': 60, 'reg_alpha': 0.0010959110820105956, 'reg_lambda': 0.0033390030495125456, 'subsample': 0.7754393901704668, 'subsample_freq': 1, 'colsample_bytree': 0.6280010606019697}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:22,258] Trial 23 finished with value: 0.8104398035485156 and parameters: {'n_estimators': 289, 'learning_rate': 0.03632278584475917, 'max_depth': 7, 'num_leaves': 14, 'min_child_samples': 81, 'reg_alpha': 0.010505452811989925, 'reg_lambda': 0.016819599130003676, 'subsample': 0.7104983695364194, 'subsample_freq': 3, 'colsample_bytree': 0.5434837825449375}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:23,912] Trial 24 finished with value: 0.8094109405188561 and parameters: {'n_estimators': 174, 'learning_rate': 0.09917573910041558, 'max_depth': 6, 'num_leaves': 10, 'min_child_samples': 20, 'reg_alpha': 0.00014406065968106327, 'reg_lambda': 0.0010395279138882092, 'subsample': 0.8231216480694763, 'subsample_freq': 2, 'colsample_bytree': 0.6951529115317593}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:26,970] Trial 25 finished with value: 0.8097525183251479 and parameters: {'n_estimators': 359, 'learning_rate': 0.07907862232917832, 'max_depth': 5, 'num_leaves': 18, 'min_child_samples': 52, 'reg_alpha': 0.04700577770053628, 'reg_lambda': 0.5718285314279228, 'subsample': 0.7706707582276869, 'subsample_freq': 4, 'colsample_bytree': 0.5041408330605246}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:29,515] Trial 26 finished with value: 0.8088941492264354 and parameters: {'n_estimators': 238, 'learning_rate': 0.05088767262444654, 'max_depth': 7, 'num_leaves': 23, 'min_child_samples': 28, 'reg_alpha': 0.0016445015920764539, 'reg_lambda': 0.03826163085569282, 'subsample': 0.6341739150054602, 'subsample_freq': 3, 'colsample_bytree': 0.5935101920555627}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:33,555] Trial 27 finished with value: 0.8099249295753875 and parameters: {'n_estimators': 500, 'learning_rate': 0.042120708469574594, 'max_depth': 6, 'num_leaves': 13, 'min_child_samples': 40, 'reg_alpha': 0.0003322518323559016, 'reg_lambda': 4.282513397167152, 'subsample': 0.8082032752082893, 'subsample_freq': 5, 'colsample_bytree': 0.7494203536268967}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:36,683] Trial 28 finished with value: 0.8061470731383567 and parameters: {'n_estimators': 309, 'learning_rate': 0.06994562464651602, 'max_depth': 8, 'num_leaves': 18, 'min_child_samples': 100, 'reg_alpha': 0.008695204542148782, 'reg_lambda': 0.21883255258291692, 'subsample': 0.8465767265912542, 'subsample_freq': 4, 'colsample_bytree': 0.6378603162409557}. Best is trial 12 with value: 0.8124997418993261.
[I 2026-07-28 09:50:40,663] Trial 29 finished with value: 0.8058043154432694 and parameters: {'n_estimators': 404, 'learning_rate': 0.01569215230697177, 'max_depth': 5, 'num_leaves': 32, 'min_child_samples': 60, 'reg_alpha': 3.9604352403168197, 'reg_lambda': 0.0007531097971364001, 'subsample': 0.892466326302673, 'subsample_freq': 2, 'colsample_bytree': 0.6972082218479732}. Best is trial 12 with value: 0.8124997418993261.

In [9]:
df = lgb_study.trials_dataframe()

In [62]:
df.sort_values(by=['value','user_attrs_overfitting_gap'],ascending=[False,True]).head()

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_learning_rate,params_max_depth,params_min_child_samples,params_n_estimators,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,params_subsample_freq,user_attrs_overfitting_gap,user_attrs_test_score_std,user_attrs_train_score_mean,user_attrs_train_score_std,state
12,12,0.813359,2026-07-27 11:33:25.499669,2026-07-27 11:33:28.519826,0 days 00:00:03.020157,0.689940,0.053656,7,22,199,23,1.180334,0.218461,0.508366,2,0.062628,0.005063,0.875987,0.003047,COMPLETE
28,28,0.813015,2026-07-27 11:34:15.476968,2026-07-27 11:34:16.996942,0 days 00:00:01.519974,0.689189,0.056726,6,51,126,12,0.788558,0.276586,0.578150,1,0.024940,0.005082,0.837955,0.001707,COMPLETE
21,21,0.812329,2026-07-27 11:33:50.637661,2026-07-27 11:33:54.173774,0 days 00:00:03.536113,0.417112,0.045305,7,47,233,37,0.098542,0.000829,0.529593,3,0.055202,0.008124,0.867531,0.001838,COMPLETE
29,29,0.811642,2026-07-27 11:34:16.999517,2026-07-27 11:34:18.996091,0 days 00:00:01.996574,0.682716,0.080396,5,66,193,10,0.000118,0.399510,0.601440,1,0.042195,0.003502,0.853838,0.001679,COMPLETE
14,14,0.811642,2026-07-27 11:33:31.465868,2026-07-27 11:33:33.192197,0 days 00:00:01.726329,0.798542,0.050635,7,36,101,18,0.274194,0.001102,0.566529,2,0.034598,0.005906,0.846240,0.002764,COMPLETE

In [10]:
df.sort_values(by=['value','user_attrs_overfitting_gap'],ascending=[False,True]).head()

,number,value,datetime_start,datetime_complete,duration,params_colsample_bytree,params_learning_rate,params_max_depth,params_min_child_samples,params_n_estimators,params_num_leaves,params_reg_alpha,params_reg_lambda,params_subsample,params_subsample_freq,user_attrs_overfitting_gap,user_attrs_test_score_std,user_attrs_train_score_mean,user_attrs_train_score_std,state
12,12,0.812500,2026-07-28 09:49:48.237399,2026-07-28 09:49:52.087151,0 days 00:00:03.849752,0.654714,0.059160,6,30,319,10,3.620272,9.996471,0.719611,4,0.032753,0.002361,0.845252,0.001289,COMPLETE
5,5,0.812329,2026-07-28 09:49:23.020145,2026-07-28 09:49:26.384196,0 days 00:00:03.364051,0.688721,0.025518,6,48,320,13,0.061303,0.739532,0.641192,4,0.033610,0.004267,0.845939,0.001407,COMPLETE
3,3,0.812157,2026-07-28 09:49:15.918736,2026-07-28 09:49:18.585775,0 days 00:00:02.667039,0.572972,0.069102,6,96,250,14,0.001263,0.001217,0.799841,1,0.057864,0.005304,0.870021,0.002625,COMPLETE
13,13,0.811470,2026-07-28 09:49:52.088851,2026-07-28 09:49:55.475832,0 days 00:00:03.386981,0.662837,0.055124,8,25,331,10,1.876296,9.985909,0.702201,4,0.038761,0.004508,0.850232,0.001685,COMPLETE
1,1,0.810783,2026-07-28 09:49:08.892292,2026-07-28 09:49:14.243652,0 days 00:00:05.351360,0.424281,0.036569,7,39,380,49,0.021917,1.824837,0.877554,5,0.082289,0.005608,0.893072,0.002576,COMPLETE

In [11]:
lgb_study.best_params

{'n_estimators': 319,
 'learning_rate': 0.05916006158291774,
 'max_depth': 6,
 'num_leaves': 10,
 'min_child_samples': 30,
 'reg_alpha': 3.6202718922173323,
 'reg_lambda': 9.996470826535594,
 'subsample': 0.7196113978680685,
 'subsample_freq': 4,
 'colsample_bytree': 0.6547144608827793}